// @ts-nocheck
/* eslint-disable */

export const STORAGE_KEYS = {
  LANG: "estipaid-lang",
  SETTINGS: "estipaid-settings-v1",
  ESTIMATOR_STATE: "estipaid-estimator-v1",
  ESTIMATE_DRAFT: "estipaid-estimate-draft-v1",
  ESTIMATES: "estipaid-estimates-v1",
  PROJECTS: "estipaid-projects-v1",
  INVOICES: "estipaid-invoices-v1",
  PENDING_CUSTOMER_USE: "estipaid-pending-customer-use-v1",
  PENDING_CUSTOMER_CREATE: "estipaid-pending-customer-create-v1",
  PENDING_CUSTOMER_EDIT: "estipaid-pending-customer-edit-v1",
  CUSTOMER_EDIT_TARGET: "estipaid-customer-edit-target-v1",
  RESTORE_DRAFT_ON_CREATE: "estipaid-restore-draft-on-create-v1",
  SELECTED_CUSTOMER_ID: "estipaid-selectedCustomerId-v1",
  SELECTED_CUSTOMER_SNAP: "estipaid-selectedCustomerSnap-v1",
  CUSTOMERS: "estipaid-customers-v1",
  CUSTOMER_RECENTS: "estipaid-customer-recent-v1",
  COMPANY_PROFILE: "estipaid-company-profile-v1",
  SUBSCRIPTION_PLAN_STATE: "estipaid-subscription-plan-state-v1",
  SUBSCRIPTION_PLAN_REMOTE_CACHE: "estipaid-subscription-plan-remote-cache-v1",
  AUDIT_EVENTS: "estipaid-audit-events-v1",
  STRIPE_CHECKOUT_SESSIONS: "estipaid-stripe-checkout-sessions-v1",
  STRIPE_CHECKOUT_CREATE_LOCKS: "estipaid-stripe-checkout-create-locks-v1",
  SCOPE_TEMPLATES: "estipaid-scope-templates-v1",
  CUSTOM_LABOR_ROLES: "estipaid-custom-labor-roles-v1",
  JOB_LEARNING_REVIEWED_CANDIDATES: "estipaid-job-learning-reviewed-candidates-v1",
  CLOUD_BACKUP_QUEUE: "estipaid-cloud-backup-queue-v1",
  CLOUD_AUTO_BACKUP_PAUSE: "estipaid-cloud-auto-backup-pause-v1",
  CLOUD_PARTIAL_RECOVERY_STATUS: "estipaid-cloud-partial-recovery-status-v1",
  CLOUD_ASSET_BINDINGS: "estipaid-cloud-asset-bindings-v1",
  CLOUD_SYNC_BASELINE: "estipaid-cloud-sync-baseline-v1",
  CLOUD_SYNC_CONFLICT_VAULT: "estipaid-cloud-sync-conflict-vault-v1",
  CLOUD_CONVERGENCE_JOURNAL: "estipaid-cloud-convergence-journal-v1",
};
